### ISSUE TITLE
Can't get rid of Quests Journal

### ISSUE THREAD

**Issue by tpeterson94** [Blackvein/Quests#464]
I cannot seem to get rid of my quests journal. When I do /quests journal it gives me a new journal, and when I run the command again it gets rid of the single journal but I still have a journal remaining

**Comment by FlyingPikachu** [comment]
Iirc this happens when the plugin is stopped (by server restart or other source) and the old journal had not been put away beforehand. While it is certainly possible to fix this, the easiest solution is to simple toss or burn the old journal. Perhaps this issue can be resubmitted once more urgent ones have been addressed. Thanks!
